---
title: matching
reportingTemplate: lowGran_ignoreShell
granularity: lowGran
# scope and resolution
endyear: 2023
periods: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
                2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
                2021, 2022, 2023]
startyear: 2001
regionmapping: [regionmappingEUplus.csv, mredgebuildings]
# EU27
regions: ["AUT", "BEL", "BGR", "CYP", "CZE", "DEU", "DNK", "ESP", "EST", "FIN",
          "FRA", "GRC", "HRV", "HUN", "IRL", "ITA", "LTU", "LUX", "LVA", "MLT",
          "NLD", "POL", "PRT", "ROU", "SVK", "SVN", "SWE"]
#ltFactor: 1.5
ltEternalShare: 0.05
boilerBan:
  var:   [stock, construction, construction, renovation]
  hs:    [ h2bo,         h2bo,         sobo,       h2bo]
  value: [    0,            0,            0,          0]
ignoreShell: TRUE

switches:
  RUNTYPE: matching
  FIXEDBUILDINGS: TRUE
  SEQUENTIALREN: TRUE
  # higher status quo bias in residential than commercial
  MINSTATUSQUORES: 0.9
  MINSTATUSQUOCOM: 0.5
...
